# -*- coding: utf-8 -*-
"""AI_Estimation_of_Air_Pollution_Percentage_in_Kyrgyzstan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sz3-StH_-CYmRJ_9FjqEYkq1vCnKksq

# AI Estimation of Air Pollution Percentage in Kyrgyzstan
## Transfer Learning Comparative Study (Regression)

# Stage 1 — Preparation
### Step 1.1: Reproducibility
"""

import tensorflow as tf
import numpy as np
import random
import os
import pandas as pd
import matplotlib.pyplot as plt

SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)

"""# Step 1.2: GPU Check"""

print("Available GPUs:", tf.config.list_physical_devices('GPU'))

"""# Stage 2 — Data Loading
### Step 2.1: Connect Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Step 2.2: Load Metadata"""

CSV_PATH = "/content/drive/MyDrive/metadata.csv"
BASE_DIR = "/content/drive/MyDrive/project_dataset"

df = pd.read_csv(CSV_PATH)
df["Image"] = df["Image"].astype(str).str.strip()

"""# Step 2.3: Resolve Paths"""

image_index = {}

for split in ["train", "val", "test"]:
    split_dir = os.path.join(BASE_DIR, split)
    for root, _, files in os.walk(split_dir):
        for f in files:
            image_index[f.lower()] = os.path.join(root, f)

def resolve_path(name):
    return image_index.get(name.lower(), "")

df["image_path"] = df["Image"].apply(resolve_path)
df = df[df["image_path"] != ""].reset_index(drop=True)

"""# Step 2.4: Train / Val / Test"""

train_df = df[df["image_path"].str.contains("/train/")].reset_index(drop=True)
val_df   = df[df["image_path"].str.contains("/val/")].reset_index(drop=True)
test_df  = df[df["image_path"].str.contains("/test/")].reset_index(drop=True)

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

"""# Stage 3 — Normalization"""

aqi_mean = train_df["AQI"].mean()
aqi_std  = train_df["AQI"].std() + 1e-8

"""# Stage 4 — Dataset Pipeline"""

from tensorflow.keras.applications.vgg16 import preprocess_input

IMG_SIZE = 224
BATCH_SIZE = 32

def load_image(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = preprocess_input(img)
    return img, label
def create_dataset(dataframe, shuffle=False):

    paths = dataframe["image_path"].values
    aqi = ((dataframe["AQI"] - aqi_mean) / aqi_std).astype("float32").values
    pm25 = dataframe["PM2.5"].astype("float32").values

    ds = tf.data.Dataset.from_tensor_slices((paths, pm25, aqi))

    if shuffle:
        ds = ds.shuffle(len(dataframe), seed=SEED)

    def load_data(path, pm_value, target):
        img = tf.io.read_file(path)
        img = tf.image.decode_jpeg(img, channels=3)
        img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
        img = preprocess_input(img)

        pm_value = tf.expand_dims(pm_value, -1)

        return (img, pm_value), target

    ds = ds.map(load_data, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(tf.data.AUTOTUNE)

    return ds

"""# Stage 5 — Model Definitions
### Model 1 — VGG16 (Image Only)
"""

def build_vgg_hybrid():

    from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling2D, Concatenate
    from tensorflow.keras.models import Model
    from tensorflow.keras.applications import VGG16

    image_input = Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    pm_input = Input(shape=(1,))

    base = VGG16(
        weights="imagenet",
        include_top=False,
        input_tensor=image_input,
        name="vgg_base"   # ← ВАЖНО
    )

    base.trainable = False

    x = base.output
    x = GlobalAveragePooling2D()(x)

    combined = Concatenate()([x, pm_input])

    x = Dense(128, activation="relu")(combined)
    output = Dense(1, activation="linear")(x)

    model = Model(inputs=[image_input, pm_input], outputs=output)

    return model

"""# Model 2 — EfficientNet



"""

def build_efficientnet_hybrid():

    from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling2D, Concatenate
    from tensorflow.keras.models import Model
    from tensorflow.keras.applications import EfficientNetB0

    image_input = Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    pm_input = Input(shape=(1,))

    base = EfficientNetB0(
        weights="imagenet",
        include_top=False,
        input_tensor=image_input,
        name="eff_base"   # ← ВАЖНО
    )

    base.trainable = False

    x = base.output
    x = GlobalAveragePooling2D()(x)

    combined = Concatenate()([x, pm_input])

    x = Dense(128, activation="relu")(combined)
    output = Dense(1, activation="linear")(x)

    model = Model(inputs=[image_input, pm_input], outputs=output)

    return model

"""# Stage 6 — Training Function"""

def train_model(model):
    model.compile(
        optimizer=tf.keras.optimizers.Adam(1e-4),
        loss=tf.keras.losses.Huber(),
        metrics=[
            tf.keras.metrics.RootMeanSquaredError(name="rmse"),
            tf.keras.metrics.MeanAbsoluteError(name="mae")
        ]
    )

    early_stop = tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    )

    reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        verbose=1
    )

    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=15,
        callbacks=[early_stop, reduce_lr],
        verbose=1
    )

    return history

"""# Stage 7 — Train Both Models"""

vgg_model = build_vgg()
vgg_history = train_model(vgg_model)

eff_model = build_efficientnet()
eff_history = train_model(eff_model)

"""# Stage 7.1 — Fine-Tuning (Hybrid)
for VGG16 Hybrid
"""

vgg_base = vgg_model.get_layer("vgg16")

vgg_base.trainable = True

for layer in vgg_base.layers[:-4]:
    layer.trainable = False

vgg_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss=tf.keras.losses.Huber(),
    metrics=[
        tf.keras.metrics.RootMeanSquaredError(name="rmse"),
        tf.keras.metrics.MeanAbsoluteError(name="mae")
    ]
)

vgg_finetune_history = vgg_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=8,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=3,
            restore_best_weights=True
        )
    ]
)

"""For EfficientNet Hybrid"""

eff_base = eff_model.get_layer("efficientnetb0")

eff_base.trainable = True

for layer in eff_base.layers[:-4]:
    layer.trainable = False

eff_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss=tf.keras.losses.Huber(),
    metrics=[
        tf.keras.metrics.RootMeanSquaredError(name="rmse"),
        tf.keras.metrics.MeanAbsoluteError(name="mae")
    ]
)

eff_finetune_history = eff_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=8,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=3,
            restore_best_weights=True
        )
    ]
)

"""# Stage 8 — Evaluation Function"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def evaluate_model(model):
    y_true = []
    y_pred = []

    for images, labels in test_ds:
        preds = model.predict(images, verbose=0).flatten()

        preds = preds * aqi_std + aqi_mean
        labels = labels.numpy() * aqi_std + aqi_mean

        y_true.extend(labels)
        y_pred.extend(preds)

    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    return rmse, mae, r2, y_true, y_pred

"""# Stage 9 — Final Testing (Official Test Evaluation)"""

vgg_rmse, vgg_mae, vgg_r2, y_true, y_pred_vgg = evaluate_model(vgg_model)
eff_rmse, eff_mae, eff_r2, _, y_pred_eff = evaluate_model(eff_model)

print("VGG16 RMSE:", vgg_rmse)
print("EfficientNet RMSE:", eff_rmse)

"""# Step 9.1: Evaluate VGG16 on Test Set"""

vgg_rmse, vgg_mae, vgg_r2, y_true, y_pred_vgg = evaluate_model(vgg_model)

print("\n===== VGG16 TEST RESULTS =====")
print(f"RMSE: {vgg_rmse:.2f}")
print(f"MAE: {vgg_mae:.2f}")
print(f"R²: {vgg_r2:.4f}")

"""# Step 9.2: Evaluate EfficientNet on Test Set"""

eff_rmse, eff_mae, eff_r2, _, y_pred_eff = evaluate_model(eff_model)

print("\n===== EfficientNet TEST RESULTS =====")
print(f"RMSE: {eff_rmse:.2f}")
print(f"MAE: {eff_mae:.2f}")
print(f"R²: {eff_r2:.4f}")

"""# Step 9.3: Comparison Table

"""

results = pd.DataFrame({
    "Model": ["VGG16", "EfficientNet"],
    "RMSE": [vgg_rmse, eff_rmse],
    "MAE": [vgg_mae, eff_mae],
    "R²": [vgg_r2, eff_r2]
})

print()
results

"""# Stage 10 — Baseline"""

baseline_pred = np.full_like(y_true, train_df["AQI"].mean())

baseline_rmse = np.sqrt(mean_squared_error(y_true, baseline_pred))
baseline_mae = mean_absolute_error(y_true, baseline_pred)
baseline_r2 = r2_score(y_true, baseline_pred)

"""# Stage 11 — Graphs
Loss
"""

plt.plot(vgg_history.history["loss"])
plt.plot(vgg_history.history["val_loss"])
plt.title("VGG16 Loss")
plt.show()

"""RMSE"""

plt.figure()
plt.plot(vgg_history.history["rmse"])
plt.plot(vgg_history.history["val_rmse"])
plt.title("VGG16 RMSE")
plt.legend(["Train", "Validation"])
plt.show()

"""true vs pred"""

plt.scatter(y_true, y_pred_vgg, alpha=0.5)
plt.plot([y_true.min(), y_true.max()],
         [y_true.min(), y_true.max()],
         color="red")
plt.title("True vs Predicted (VGG16)")
plt.show()

"""# Error Distribution"""

errors = y_true - y_pred_vgg
plt.hist(errors, bins=30)
plt.title("Prediction Error Distribution")
plt.show()